* 🛠 @amory/watch
:properties:
:header-args: :cache yes :comments org :padline yes :results silent
:header-args:mjs: :noweb tangle :shebang "#!/usr/bin/env node"
:end:
#+startup: showall nohideblocks hidestars indent

#+begin_quote
Monitor file system changes with node and chokidar using a child process.
#+end_quote

** Quick Start

#+begin_example sh :tangle no
yarn add @amory/watch

cp node_modules/@amory/watch/*.mjs .
#+end_example

** License

#+begin_quote :noweb-ref license.mit.txt
Copyright (c) 2018 [[https://github.com/ptb][Peter T Bosse II]]

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#+end_quote

** Example

#+begin_example js
import _debug from "debug"

import watch, { pubSub } from "./watch.mjs"

const debug = _debug ("@amory:watch")
const watchdir = process.argv[2] || process.cwd ()

const thread = watch (debug, "./agent.mjs")

pubSub.sub ((msg) => {
  if (msg.evt === "start") {
    thread.send ({ "cmd": "add", "opts": watchdir })
  }
})
#+end_example
